[package]
name = "tree_aggregator"
type = "bin"
authors = ["Apertrue Social"]
compiler_version = ">=1.0.0"
description = "TreeAggregator: Combines 2 proofs into 1 for binary tree aggregation (reusable at any tree level)"

[dependencies]
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.3", directory = "barretenberg/noir/bb_proof_verification" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
