
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import ApertrueVerifierContractArtifactJson from '../target/apertrue_verifier-ApertrueVerifier.json' with { type: 'json' };
export const ApertrueVerifierContractArtifact = loadContractArtifact(ApertrueVerifierContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ApertrueVerifier;
 */
export class ApertrueVerifierContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, ApertrueVerifierContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ApertrueVerifierContract {
    return Contract.at(address, ApertrueVerifierContract.artifact, wallet) as ApertrueVerifierContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, initial_vk_hash: FieldLike) {
    return new DeployMethod<ApertrueVerifierContract>(PublicKeys.default(), wallet, ApertrueVerifierContractArtifact, (instance, wallet) => ApertrueVerifierContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, initial_vk_hash: FieldLike) {
    return new DeployMethod<ApertrueVerifierContract>(publicKeys, wallet, ApertrueVerifierContractArtifact, (instance, wallet) => ApertrueVerifierContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ApertrueVerifierContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ApertrueVerifierContract['methods'][M]>
  ) {
    return new DeployMethod<ApertrueVerifierContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ApertrueVerifierContractArtifact,
      (instance, wallet) => ApertrueVerifierContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ApertrueVerifierContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ApertrueVerifierContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'vk_hash' | 'verified_notes' | 'verification_root' | 'tree_size'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
vk_hash: {
      slot: new Fr(3n),
    },
verified_notes: {
      slot: new Fr(5n),
    },
verification_root: {
      slot: new Fr(6n),
    },
tree_size: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'admin' | 'vk_hash' | 'verified_notes' | 'verification_root' | 'tree_size'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct, initial_vk_hash: field) */
    constructor: ((admin: AztecAddressLike, initial_vk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_tree_size() */
    get_tree_size: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_verification_root() */
    get_verification_root: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_vk_hash() */
    get_vk_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_merkle_root(new_root: field, new_tree_size: field) */
    update_merkle_root: ((new_root: FieldLike, new_tree_size: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_and_store(proof: array, vk: array, vk_hash: field, public_values: array, image_count: field, trust_list_root: field, epoch_week: field, owner: struct) */
    verify_and_store: ((proof: FieldLike[], vk: FieldLike[], vk_hash: FieldLike, public_values: FieldLike[], image_count: FieldLike, trust_list_root: FieldLike, epoch_week: FieldLike, owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
